version: '3'

services:
  products-microservice:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodbdatabase

  mongodbdatabase:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodbData:/data/db
